/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import java.util.*;
import java.text.*;
import java.awt.print.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import javax.swing.JEditorPane;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ajeet
 */

public final class Main_Oage extends javax.swing.JFrame {
     Connection con;
     PreparedStatement pst;
     ResultSet rs;
     int n,tax=0,hsn=0,ptr=0;
     String rupee="",picu="";
     StringBuilder typ =new StringBuilder("ORIGINAL "); 
     String text,html;
     String str1=null,type1=null; 
     public String cos_name=null,cos_address=null,cos_gst=null,type=null; 
     public String cos_mobile=null,cos_state=null,cos_state_code=null;
     int Quant1 = 0,serial=0,i=0,i0=1,tp=0;
     int akm=0,akm1=0,ajeet=0;
     static int mkv=1;
     float ptr1=0,discount1=0,tmt =0;
     String Dateformat=null;
     public Main_Oage() {
        initComponents();
        Show_Data();
    }
 public void close()
 {
  WindowEvent windo = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
  Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windo);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Quantity_Add = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        Cos_Name = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Cos_Address = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Cos_Gst = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Cos_Mobile = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Cos_State = new javax.swing.JTextField();
        Cos_State_Code = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        che2 = new javax.swing.JRadioButton();
        che1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        invoice = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Page");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 150, 166), 8, true));

        jButton5.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jButton5.setText("Reciept");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jButton7.setText("Total");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jButton9.setText("Reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 1330, -1));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 150, 166), 8, true));

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 650, 290));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 150, 166), 8, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, 30));

        jLabel3.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel3.setText("Date");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 70, 30));

        Quantity_Add.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Quantity_Add.setText("0");
        Quantity_Add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Quantity_AddKeyTyped(evt);
            }
        });
        jPanel5.add(Quantity_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 150, 30));

        Id.setEditable(false);
        Id.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdKeyTyped(evt);
            }
        });
        jPanel5.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 150, 30));

        jButton3.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 150, 40));

        jLabel5.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel5.setText("Firm Name");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 30));

        Name.setEditable(false);
        Name.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });
        jPanel5.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 150, 30));

        jLabel11.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel11.setText("Total Cost");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 90, 40));

        Total.setEditable(false);
        Total.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TotalKeyTyped(evt);
            }
        });
        jPanel5.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 150, 40));

        Cos_Name.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Cos_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cos_NameActionPerformed(evt);
            }
        });
        Cos_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Cos_NameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cos_NameKeyTyped(evt);
            }
        });
        jPanel5.add(Cos_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, 30));

        jLabel13.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(213, 42, 42));
        jLabel13.setText("Billed To");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        jLabel14.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(207, 40, 40));
        jLabel14.setText("Product Details");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        Cos_Address.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Cos_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cos_AddressActionPerformed(evt);
            }
        });
        Cos_Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cos_AddressKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Cos_AddressKeyReleased(evt);
            }
        });
        jPanel5.add(Cos_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 150, 30));

        jLabel15.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel15.setText("Address");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 30));

        jLabel16.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel16.setText("GST/UID");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        Cos_Gst.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Cos_Gst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cos_GstActionPerformed(evt);
            }
        });
        Cos_Gst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cos_GstKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Cos_GstKeyReleased(evt);
            }
        });
        jPanel5.add(Cos_Gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, 30));

        jLabel17.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel17.setText("Mobile ");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 30));

        Cos_Mobile.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Cos_Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cos_MobileActionPerformed(evt);
            }
        });
        Cos_Mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Cos_MobileKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cos_MobileKeyTyped(evt);
            }
        });
        jPanel5.add(Cos_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 150, 30));

        jLabel18.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel18.setText("Id");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 60, 30));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 230, 10));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 490, 10));

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton1.setText("Feed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 150, 40));

        jLabel19.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel19.setText("State");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 30));

        Cos_State.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Cos_State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cos_StateActionPerformed(evt);
            }
        });
        Cos_State.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Cos_StateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cos_StateKeyTyped(evt);
            }
        });
        jPanel5.add(Cos_State, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 150, 30));

        Cos_State_Code.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Cos_State_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cos_State_CodeActionPerformed(evt);
            }
        });
        Cos_State_Code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Cos_State_CodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cos_State_CodeKeyTyped(evt);
            }
        });
        jPanel5.add(Cos_State_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 150, 30));

        jLabel20.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel20.setText("State Code");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, 30));

        jLabel21.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel21.setText("Invoice No");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 100, 30));

        buttonGroup4.add(che2);
        che2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        che2.setText("Tax");
        che2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                che2MouseClicked(evt);
            }
        });
        che2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                che2ActionPerformed(evt);
            }
        });
        jPanel5.add(che2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        buttonGroup4.add(che1);
        che1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        che1.setText("Sale");
        che1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                che1MouseClicked(evt);
            }
        });
        che1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                che1ActionPerformed(evt);
            }
        });
        jPanel5.add(che1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("TIBRA TEXTILES");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 220, -1));

        jLabel22.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel22.setText("Discount");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 100, 30));

        discount.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        discount.setText("0");
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });
        discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discountKeyTyped(evt);
            }
        });
        jPanel5.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 150, 30));

        jDateChooser1.setBackground(new java.awt.Color(52, 137, 165));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jPanel5.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 150, 30));

        jLabel6.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel6.setText("Quantity");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));

        invoice.setEditable(false);
        invoice.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceActionPerformed(evt);
            }
        });
        invoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoiceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                invoiceKeyTyped(evt);
            }
        });
        jPanel5.add(invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 100, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 560));

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 150, 166), 8, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 240));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 650, 260));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invoice", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 110, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int Qua,num;
       int index = jTable1.getSelectedRow();
       TableModel model = jTable1.getModel();
       Id.setText(model.getValueAt(index, 0).toString());
       Name.setText(model.getValueAt(index, 1).toString());
       num = Integer.parseInt(model.getValueAt(index, 2).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    /* if(akm1!=1)
        {
          JOptionPane.showMessageDialog(null,"First Click on Total");
          return;
        }*/
    
     String pre="ORIGINAL "; 
     try
       {
           pre+=html;
           typ.append(html);
           jEditorPane1.setName(pre);
           jEditorPane1.print();
           /*typ="DUPLICATE";
           text = typ + html;
           jEditorPane1.setText(text);
           jEditorPane1.print();
           typ="TRIPLICATE";
           text = typ + html;
           jEditorPane1.setText(text);
           jEditorPane1.print();*/
       }
       catch(PrinterException e)
       {
           System.err.format("Connect your Printer Please!!!", e.getMessage());
       }  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int yesOrNo = JOptionPane.showConfirmDialog(null,"Do you want to close it?"+"Exit"+JOptionPane.YES_NO_OPTION);
        if(yesOrNo==0)
        {   
          close();
        }
        else
        {}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
        if(ajeet!=1)
        {
          JOptionPane.showMessageDialog(null,"First add Products");
          return;
        } 
        float ttm=0,itm=0,ctm=0,stm=0,cgst=0,sgst=0,igst=0;
        pkm((int)(Quant1+ptr1-discount1));
        pkv((int)(ptr1));
        if (Cos_State_Code.getText().equals("09"))
        {
          cgst = tax/2;
          ctm=(float)ptr1/2;
          sgst = tax/2;
          stm=(float)ptr1/2;
        }
        else
        {
          igst = tax;
          itm=ptr1;
        }
        html+="</td></tr><tr><td width=\"40\"></td><td width=\"253\" align=\"right\"><b>Total=</b></td><td width=\"60\"></td><td width=\"40\"></td><td width=\"60\"></td><td width=\"60\"></td><td width=\"40\">"+discount1+"</td><td width=\"80\">"+(int)(Quant1+ptr1-discount1)+"</td></tr>";
        html+="<tr><td colspan=\"8\" width=\"635\"><b>"+rupee+"</b></td></tr><tr><td width=\"100\" rowspan=\"2\">HSN/SAC</td><td rowspan=\"2\">Taxable Value</td><td colspan=\"2\">IGST</td><td colspan=\"2\">Central Tax</td><td colspan=\"2\">State Tax</td></tr>"
                + "<tr><td>Rate</td><td>Amount</td><td>Rate</td><td>Amount</td><td>Rate</td><td>Amount</td></tr>"
                + "<tr><td>8507</td><td>"+(Quant1-discount1)+"</td><td>"+igst+"</td><td>"+itm+"</td><td>"+cgst+"</td><td>"+ctm+"</td><td>"+sgst+"</td><td>"+stm+"</td></tr><tr><td align=\"right\"><b>Total</b></td><td><b>"+(Quant1-discount1)+"</b></td><td></td><td><b>"+itm+"</b></td><td></td><td><b>"+ctm+"</b></td><td></td><td><b>"+stm+"</b></td></tr>"
                + "<tr><td colspan=\"8\"><b>"+picu+"</b></td></tr>"
                + "<tr><td colspan=\"2\"><b><font size=\"3px\">Terms and Conditions</font></b></td><td colspan=\"6\"><b>Company's Bank Details</b></td></tr>"
                + "<tr><td rowspan=\"4\" colspan=\"2\"><font size=\"5px\">GOODS ONCE SOLD CAN NOT BE RETURNED<br><font size=\"5px\">INTEREST WILL BE CHARGED @24%P.A.3</font><br>"
                + "ALL DISPUTES SUBJECT TO MEERUT JURIDICTION ONLY 4 GOODS WILL BE CHANGE<br>WITHIN 15 DAYS"
                + "</td><td rowspan=\"4\" colspan=\"6\">Bank Name &nbsp ICICI BANK(EVES CHOWK)&nbsp IDBI BANK(RTO ROAD)<br>"
                + "Account Number &nbsp 126605500775 &nbsp 0278102000019983<br>"
                + "IFSC Code &nbsp ICIC0001266 &nbsp IBKL0000278<br>"
                + "Branch &nbsp Meerut</td></tr><tr></tr><tr></tr><tr></tr>"
                + "<tr><td colspan=\"4\" rowspan=\"4\">Costumer's Seal and Signature<br><br><br></td><td align=\"right\" colspan=\"4\" rowspan=\"4\"><b>for TIBRA TEXTILES</b><br><br>Prepared by &nbsp&nbsp&nbsp Authorised By</td></tr><tr></tr><tr></tr><tr></tr><hr>"
                + "</table>";
	html+="</body></html>";
        jEditorPane1.setText(html);
        
        float total,total1;
        total = Quant1;
        total1= Quant1;
        String date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        Total.setText(String.valueOf(total1+ptr1-discount1));
       
       Calendar time = Calendar.getInstance();
       time.getTime();
       SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
       tTime.format(time.getTime());
       SimpleDateFormat tDate = new SimpleDateFormat("yyyy:MM:dd");
       tDate.format(time.getTime());
       if(che1.isSelected())
       {
       try
        {
            String sql = "INSERT INTO `Sales`(`S_Name`, `S_Mobile`,`S_Date`, `S_Price`) VALUES (?,?,?,?)";
            con = (Connection) DriverManager.getConnection("jdbc:sqlite:C:/sqllite/ajeet.db");
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1,Cos_Name.getText());
            pst.setString(2,Cos_Mobile.getText());
            pst.setString(3, date);
            pst.setFloat(4, total1+ptr1-discount1);
            pst.executeUpdate();
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Could not Inserted in Salse");
        }
       }
       else
       {
        try
        {
            
            String sql = "INSERT INTO `Tax`(`T_Name`, `T_Mobile`,`T_Date`, `T_Price`) VALUES (?,?,?,?)";
            con = (Connection) DriverManager.getConnection("jdbc:sqlite:C:/sqllite/ajeet.db");
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1,Cos_Name.getText());
            pst.setString(2,Cos_Mobile.getText());
            pst.setString(3, date);
            pst.setFloat(4, total1+ptr1-discount1);
            pst.executeUpdate();

        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Could not Inserted in Tax");
        }
       }
       Quant1=0;
       akm1=1;
    }//GEN-LAST:event_jButton7ActionPerformed
   public void pkm(int x)
   {
    n=x;
      pw((n/1000000000)," Hundred");
      pw((n/10000000)%100," Crore");
      pw(((n/100000)%100)," Lakh");
      pw(((n/1000)%100)," Thousand");
      pw(((n/100)%10)," Hundred");
      pw((n%100)," ");
    }
   public void pw(int n,String ch)
   {
       
    String  one[]={" "," One"," Two"," Three"," Four"," Five"," Six"," Seven"," Eight"," Nine"," Ten"," Eleven"," Twelve"," Thirteen"," Fourteen","Fifteen"," Sixteen"," Seventeen"," Eighteen"," Nineteen"};

    String ten[]={" "," "," Twenty"," Thirty"," Forty"," Fifty"," Sixty"," Seventy"," Eighty"," Ninety"};
   
    if(n > 19) 
    { 
        rupee+=(ten[n/10]+" "+one[n%10]);
    }
    else 
    {
       rupee+=(one[n]);
    }
      if(n!=0)
      rupee+=(ch);
     }
   
   
   public void pkv(int x)
   {
    n=x;
      pv((n/1000000000)," Hundred");
      pv((n/10000000)%100," Crore");
      pv(((n/100000)%100)," Lakh");
      pv(((n/1000)%100)," Thousand");
      pv(((n/100)%10)," Hundred");
      pv((n%100)," ");
    }
   public void pv(int n,String ch)
   {
       
    String  one[]={" "," One"," Two"," Three"," Four"," Five"," Six"," Seven"," Eight"," Nine"," Ten"," Eleven"," Twelve"," Thirteen"," Fourteen","Fifteen"," Sixteen"," Seventeen"," Eighteen"," Nineteen"};

    String ten[]={" "," "," Twenty"," Thirty"," Forty"," Fifty"," Sixty"," Seventy"," Eighty"," Ninety"};
   
    if(n > 19) 
    { 
        picu+=(ten[n/10]+" "+one[n%10]);
    }
    else 
    {
       picu+=(one[n]);
    }
    if(n!=0)
      picu+=(ch);
     }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      Update_Login up = new Update_Login();
      up.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try
        {jEditorPane1.print();
        }
        catch(Exception e)
        {}
        jEditorPane1.setText("");
        Id.setText("");
        Name.setText("");
        Quantity_Add.setText("");
        Total.setText("");
        akm=0;
        akm1=0;
        i=0;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void che1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_che1ActionPerformed
        invoice.setEnabled(true);
        invoice.setEditable(true);
        try
        {
         String sql = "SELECT `Sale` FROM `Invoice` WHERE `Sale`>0 ORDER BY `Sale`";
         con = (Connection) DriverManager.getConnection("jdbc:sqlite:C:/sqllite/ajeet.db");
         pst = (PreparedStatement) con.prepareStatement(sql);
         rs = pst.executeQuery();
         jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(null,"Fault in Sale Invoice");
        }
    }//GEN-LAST:event_che1ActionPerformed

    private void che2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_che2ActionPerformed
        invoice.setEnabled(true);
        invoice.setEditable(true);
        try
        {
         String sql = "SELECT `Tax` FROM `Invoice1` WHERE `Tax`>0 ORDER BY `Tax`";
         con = (Connection) DriverManager.getConnection("jdbc:sqlite:C:/sqllite/ajeet.db");
         pst = (PreparedStatement) con.prepareStatement(sql);
         rs = pst.executeQuery();
         jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(null,"Fault in Tax Invoice");
        }
    }//GEN-LAST:event_che2ActionPerformed

    private void Cos_State_CodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_State_CodeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_State_CodeKeyReleased

    private void Cos_State_CodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_State_CodeKeyTyped
        Child_Biling number = new Child_Biling();
        try{
            number.NumbersOnly(evt);
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_Cos_State_CodeKeyTyped

    private void Cos_State_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cos_State_CodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_State_CodeActionPerformed

    private void Cos_StateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_StateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_StateKeyReleased

    
    private void Cos_StateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_StateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_StateKeyTyped

    private void Cos_StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cos_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_StateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        i=50;
        if("".equals(date))
        {
          JOptionPane.showMessageDialog(null,"Select date below Please!!!");
          return ;
        }
        while("".equals(Cos_Name.getText()))
        {
          JOptionPane.showMessageDialog(null,"Fill Name Please!!!");
          return ;
        }
        while("".equals(Cos_Address.getText()))
        {
          JOptionPane.showMessageDialog(null,"Fill Address Please!!!");
          return ;
        }
        while("".equals(Cos_State.getText()))
        {
          JOptionPane.showMessageDialog(null,"Fill State Please!!!");
          return ;
        }
        while("".equals(Cos_State_Code.getText()))
        {
          JOptionPane.showMessageDialog(null,"Fill State Number Please!!!");
          return ;
        }
        while((!che1.isSelected())&&(!che2.isSelected()))
        {
          JOptionPane.showMessageDialog(null,"Select any Invoice type!!!");
          return ;
        }
        while("".equals(invoice.getText()))
        {
          JOptionPane.showMessageDialog(null,"Enter the invoice Number!!!");
          return ;
        }
        if(che1.isSelected())
        {  
        try
        {
            String sql = "INSERT INTO `Invoice`(`Sale`) VALUES (?)";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1,invoice.getText());
            pst.executeUpdate();
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error in Sale Invoice number");
        }
        
        }
        if(che2.isSelected())
        {
        try
        {
            String sql = "INSERT INTO `Invoice1`(`Tax`) VALUES (?)";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1,invoice.getText());
            pst.executeUpdate();
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error in Tax Invoice number");
        }
        }
        cos_name = Cos_Name.getText().toUpperCase();
        cos_address = Cos_Address.getText().toUpperCase();
        cos_gst = Cos_Gst.getText().toUpperCase();
        cos_mobile = Cos_Mobile.getText();
        cos_state = Cos_State.getText();
        cos_state_code = Cos_State_Code.getText();
        Dateformat=date;
        start();
        jEditorPane1.setText(html); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Cos_MobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_MobileKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_MobileKeyReleased

    private void Cos_MobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_MobileKeyTyped
       Child_Biling number = new Child_Biling();
        try{
            number.NumbersOnly(evt);
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_Cos_MobileKeyTyped

    private void Cos_GstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_GstKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_GstKeyReleased

    private void Cos_GstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_GstKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_GstKeyTyped

    private void Cos_GstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cos_GstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_GstActionPerformed

    private void Cos_AddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_AddressKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_AddressKeyReleased

    private void Cos_AddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_AddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_AddressKeyTyped

    private void Cos_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cos_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_AddressActionPerformed

    private void Cos_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_NameKeyReleased

    }//GEN-LAST:event_Cos_NameKeyReleased

    private void Cos_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cos_NameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_NameKeyTyped

    private void Cos_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cos_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cos_NameActionPerformed

    private void TotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalKeyReleased

    private void TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalKeyTyped

    private void NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyReleased
        
    }//GEN-LAST:event_NameKeyReleased

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
       /* Child_Biling string = new Child_Biling();
        try{
            string.StringOnly(evt);
        }
        catch(Exception e)
        {
        }*/

    }//GEN-LAST:event_NameKeyTyped

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ajeet=1;
        if(i==0)
        {
             JOptionPane.showMessageDialog(null, "First Click on Feed");
             return;
        }
        int disc=0,piece,cost=1,prc=0,bal=0;
        String date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        Dateformat = date;
        if(date.equalsIgnoreCase(""))
        {
             JOptionPane.showMessageDialog(null, "First choose Date");
             return;
        }
        else
        {
         if(Id.getText().equalsIgnoreCase(""))
         {
             JOptionPane.showMessageDialog(null, "Select any Item");
             return;
         }
         else
         {
         try
         {
            String sql = "SELECT Gst,Hsn_No FROM `Costumer` WHERE `Name`=?";
            con = (Connection) DriverManager.getConnection("jdbc:sqlite:C:/sqllite/ajeet.db");
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, Name.getText());
            rs = pst.executeQuery();
            while(rs.next())
            {
                tax = rs.getInt(1);
                hsn = rs.getInt(2);
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"No Gst on this Product");
        }
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String str = model.getValueAt(index, 1).toString();
        piece = Integer.parseInt(model.getValueAt(index, 2).toString());
        ptr = Integer.parseInt(model.getValueAt(index, 3).toString());
        prc = ptr;
        cost = Integer.parseInt(Quantity_Add.getText());
        while((piece-cost)<0)
        {
            JOptionPane.showMessageDialog(null,"Enter Less Quantity");
            Quantity_Add.setText("");
            cost = Integer.parseInt(Quantity_Add.getText());
        }
        ptr=ptr*cost;
        bal=ptr;
        Quant1 = Quant1 + ptr;
        disc = Integer.parseInt(discount.getText());
        discount1 = discount1 + ptr*disc/100;
        ptr =ptr-ptr*disc/100; 
        ptr1=ptr1+(float)ptr*tax/100;
        html+="<tr><td  width=\"40\">"+mkv+"</td><td width=\"253\">"+str+"</td><td width=\"60\">"+hsn+"</td><td width=\"40\">"+tax+"</td><td width=\"60\">"+cost+"</td><td width=\"60\">"+prc+"</td><td width=\"40\">"+disc+"</td><td width=\"80\">"+bal+"<br></td></tr>";
        jEditorPane1.setText(html);
        mkv++;
        try
        {
            String sql = "INSERT INTO `History`(`H_Name`,`H_Quantity`,`H_Price`,`H_Date`) VALUES (?,?,?,?)";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1,Name.getText());
            pst.setString(2,Quantity_Add.getText());
            pst.setInt(3,ptr);
            pst.setString(4, date);
            pst.executeUpdate();
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Could not Updated to History!!");
        }
        try
        {
            String sql = "UPDATE `Costumer` SET `Quantity`=? WHERE Name=?";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(2,Name.getText());
            pst.setInt(1,(piece-cost));
            pst.executeUpdate();
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Could not Updated Final Quantity in Main Table");
        }
        Id.setText("");
        Name.setText("");
        Quantity_Add.setText("");
        discount.setText("");
         }
        }
        akm=1;
        Show_Data();
       
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void IdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdKeyReleased
        
    }//GEN-LAST:event_IdKeyReleased

    private void IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdKeyTyped
        Child_Biling number = new Child_Biling();
        try{
            number.NumbersOnly(evt);
        }
        catch(Exception e)
        {
        }

    }//GEN-LAST:event_IdKeyTyped

    private void Quantity_AddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Quantity_AddKeyTyped
        Child_Biling number = new Child_Biling();
        try{
            number.NumbersOnly(evt);
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_Quantity_AddKeyTyped

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountActionPerformed

    private void discountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_discountKeyTyped

    private void discountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_discountKeyReleased

    private void Cos_MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cos_MobileActionPerformed
    
    }//GEN-LAST:event_Cos_MobileActionPerformed

    private void invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceActionPerformed

    private void invoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceKeyReleased

    private void invoiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceKeyTyped
       Child_Biling number = new Child_Biling();
        try{
            number.NumbersOnly(evt);
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_invoiceKeyTyped

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       int index = jTable2.getSelectedRow();
       TableModel model = jTable2.getModel();
       invoice.setText(model.getValueAt(index, 0).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void che1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_che1MouseClicked
       type1 = "SALE";
    }//GEN-LAST:event_che1MouseClicked

    private void che2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_che2MouseClicked
        type1 = "TAX";
    }//GEN-LAST:event_che2MouseClicked

    void start()
    {
        String in=invoice.getText();
	try
	{
	html="<html><head><style> body{mrgin-top:0px;} table {border-collapse: collapse; border-style:hidden; padding: 0px 0px 0px 0px; border-spacing:0px;} table td {border-width: 1px;  border-color:black; font-size: 7px; }</style></head>";
	html+="<body bgcolor=white><table cellpadding=\"0\" cellspacing=\"0\"><tr><td colspan=\"8\"><center><b>"+type1+" INVOICE</b></center><br>"
                + "<tr>"
                   + "<td rowspan=\"2\" colspan=\"2\">"
                      + "<b>TIBRA TEXTILES</b><br>"
                      +"HOUSE NO. 333 GALI NO 2 KARIM NAGAR <br>MEERUT U.P.Mob No: 9997391833 State Code:09<br></td><td colspan=\"3\">Invoice No:<b>GST/"+in+"</b></td><td colspan=\"3\">Date:<b>"+Dateformat+"</b></td>"
                      + "<tr><td colspan=\"3\">Delivery Note.&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td><td colspan=\"3\">Mode/Terms of Payment</td></tr>"
                   + "</tr>"
                   + "<tr>"
                            +"<td rowspan=\"6\" colspan=\"2\"><b>Buyer's Details</b><br>Name:"+cos_name+"<br>Address:"+cos_address+"<br>GSTIN/UIN:"+cos_gst+"<br>State No:"+cos_state_code+"<br>State Name:"+cos_state+"<br>Place of Supply:"+cos_address+"</td>"
                            +"<td colspan=\"3\">Supplier's Ref.</td><td colspan=\"3\">Other Reference(S)</td></tr>"
                            +"<td colspan=\"3\">Buyer's Order No.</td><td colspan=\"3\">Dated</td></tr>"
                            +"<tr><td colspan=\"3\">Despatch Document No.</td><td colspan=\"3\">Delivery Note Date</td></tr>"
                            +"<tr><td colspan=\"3\">Dispatched Through</td><td colspan=\"3\">Destination</td></tr>"
                            +"<tr><td colspan=\"3\">Terms of Delivery</td><td colspan=\"3\">None</td></tr>"
                            +"<tr><td colspan=\"3\">Other</td><td colspan=\"3\">For General</td></tr>"
                +"<tr>"
                   + "<td width=\"40\">S.NO.</td>"
                   + "<td width=\"253\">DESCRIPTION OF GOODS</td>"
                   + "<td width=\"60\">HSN/SAC</td>"
                   + "<td width=\"40\">GST</td>"
                   + "<td width=\"60\">Quantity</td>"
                   + "<td width=\"60\">Rate</td>"
                   + "<td width=\"40\">Disc</td>"
                   + "<td  width=\"80\">Amount</td>"
                + "</tr>";
              
	setVisible(true);
	setDefaultCloseOperation(EXIT_ON_CLOSE);
        //ed1.print();
	}
	catch(Exception e)
	{
		System.out.println("Some problem has occured"+e.getMessage());
	}
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Oage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Oage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Oage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Oage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Oage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cos_Address;
    private javax.swing.JTextField Cos_Gst;
    private javax.swing.JTextField Cos_Mobile;
    private javax.swing.JTextField Cos_Name;
    private javax.swing.JTextField Cos_State;
    private javax.swing.JTextField Cos_State_Code;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Quantity_Add;
    private javax.swing.JTextField Total;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton che1;
    private javax.swing.JRadioButton che2;
    private javax.swing.JTextField discount;
    private javax.swing.JTextField invoice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void Show_Data() {
        try
        {
            String sql = "SELECT Id,Name,Quantity,Price FROM `Costumer` "+"WHERE Id >0 ORDER BY Id";
            con = (Connection) DriverManager.getConnection("jdbc:sqlite:C:/sqllite/ajeet.db");
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jEditorPane1.setText(html);
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Not Found");
        }
    }
}
